[AP-29] filter by budget
naruhiyo/appetizer pull request #13
Opened 2021-05-17 22:55 UTC by narugit

### 先行PR
なし

### 内容
- JIRA: [AP-29](https://naruhiyo.atlassian.net/browse/AP-29)

### 動作確認項目
- 高々100件の取得データから4件を抽出していること
- settings.jsonで設定した`priceRange`を含む、最小範囲の予算コードで検索できていること

### 動作確認結果
- settings.jsonに設定した`priceRange`に基づいて検索結果が返却されている
  - settings.jsonのpriceRange: 2200~3300
  - 検索結果の1件目のbudget.name: 3001~4000
- 高々100件の取得データから4件を抽出していること
  - `Num of all response data`, `Num of selected data`箇所

![image](https://user-images.githubusercontent.com/28133383/118565753-b3e0a000-b7ad-11eb-8ba9-aeb5eac16c6f.png)

#### settings.json
![image](https://user-images.githubusercontent.com/28133383/118565814-d07cd800-b7ad-11eb-84b4-465ebcffe90a.png)

### 備考
なし

2021-05-17 22:58 UTC, narugit commented on src/lib/api/HotpepperApiForm.ts
> +]
この定義どこに置くのが良いんだろう
- `src/lib/api/HotpepperBudget.ts`
- `src/lib/definition/HotpepperBudget.ts`
- 別の場所？

2021-05-17 23:18 UTC, narugit commented on src/commands/HotpepperSearch.ts
> +    const priceMax = priceRange === undefined ? 0 : priceRange[1];
```suggestion
    const priceMax = priceRange === undefined ? priceMin : priceRange[1];
```
こうしないと、priceMin ≦ priceMaxの関係が保たれない

2021-05-17 23:19 UTC, narugit commented on src/lib/api/HotpepperApiForm.ts
> +//       - 100個取得して、そこからランダムに4個選択する
```suggestion
```

2021-05-17 23:21 UTC, narugit commented on src/commands/HotpepperSearch.ts
> +import { prependListener } from 'process';
```suggestion
```
不要

2021-05-17 23:50 UTC, hiyoko3 requested changes

2021-05-17 23:50 UTC, hiyoko3 commented on src/lib/api/HotpepperApi.ts
> +      let selectedShops = responseData.then(responses => {
ここはデータの加工なのでAPIの処理としてやることではないため、
HotpepperShopResponseListみたいなクラスを作ってそこで処理させたいですね

2021-05-17 23:50 UTC, hiyoko3 commented on src/lib/api/HotpepperApiForm.ts
> +  public static newFromConfig(budgetMin: number, budgetMax: number, lat: number, lng: number): HotpepperApiFormImpl {
これはAPIのパラメーターを作成しているような処理に見受けられるので、インスタンスメソッドで`to_api`みたいなメソッドにしてはどうでしょうか？

2021-05-17 23:50 UTC, hiyoko3 commented on src/lib/api/HotpepperApiForm.ts
> +const BudgetList: Array<Budget> = [
APIフォームとは別の概念なので別クラスに切り分けたい

2021-05-17 23:50 UTC, hiyoko3 commented on src/commands/HotpepperSearch.ts
> +    const priceRange = generalConf.priceRange?.sort();
ここの処理が newFromConfigに該当するのかなと思いますがいかがでしょうか？

ここはController層なので極力ロジックは書かずにいたほうが良いかと思います。

2021-05-17 23:55 UTC, narugit commented on src/lib/api/HotpepperApiForm.ts
> +const BudgetList: Array<Budget> = [
定義どこに置くのがよさめかな？
- `src/lib/api/HotpepperBudget.ts`
- `src/lib/definition/HotpepperBudget.ts`
- 別の場所？

2021-05-18 00:09 UTC, narugit commented on src/lib/api/HotpepperApiForm.ts
> +  public static newFromConfig(budgetMin: number, budgetMax: number, lat: number, lng: number): HotpepperApiFormImpl {
https://github.com/naruhiyo/appetizer/pull/13#discussion_r633936718 の話と合わせて議論したいのですが、

newFromConfigの責務としては、下記認識でOK？

- settings.jsonから設定値を取得して、
- APIのパラメータ(API Form)を生成して、
- hotpepperApiFormImplのインスタンスを返却する

2021-05-18 00:10 UTC, narugit commented on src/lib/api/HotpepperApiForm.ts
> +  public static newFromConfig(budgetMin: number, budgetMax: number, lat: number, lng: number): HotpepperApiFormImpl {
上記Yesなら、

> APIのパラメータ(API Form)を生成して、

ここを`to_api()`に切り出すって感じかな。

2021-05-18 00:18 UTC, narugit commented on src/lib/api/HotpepperApi.ts
> +      let selectedShops = responseData.then(responses => {
> ここはデータの加工なのでAPIの処理としてやることではないため

Hotpepper APIを直接叩くクラスでは、Hotpepper APIのレスポンスをそのまま返却するメソッドしか置くべきじゃないってことかな？

> HotpepperShopResponseListみたいなクラスを作ってそこで処理させたいですね

Hotpepper APIを叩いた結果を整形するんだったら、APIを叩く側の用途に応じたWrapper層をつくったほうが良いよってこと？それはAPIを叩く側が増えたときの拡張性を意識してる感じ？

2021-05-18 14:35 UTC, hiyoko3 commented on src/lib/api/HotpepperApi.ts
> +      let selectedShops = responseData.then(responses => {
> Hotpepper APIを直接叩くクラスでは、Hotpepper APIのレスポンスをそのまま返却するメソッドしか置くべきじゃないってことかな？

そう！

> Hotpepper APIを叩いた結果を整形するんだったら、APIを叩く側の用途に応じたWrapper層をつくったほうが良いよってこと？それはAPIを叩く側が増えたときの拡張性を意識してる感じ？

そうだね、多分テストを書くことを意識しながらソースコードを書いてみるとイメージしやすいかも。
APIのテストを書いてるはずなのに実際の中身は整形のテストも必要ですってなったらおかしいな、、ってイメージです！

2021-05-18 14:35 UTC, hiyoko3 commented on src/lib/api/HotpepperApiForm.ts
> +  public static newFromConfig(budgetMin: number, budgetMax: number, lat: number, lng: number): HotpepperApiFormImpl {
> newFromConfigの責務としては、下記認識でOK？

そそ、メソッド名にもあるようにConfig値からインスタンスを生成するまでがこのメソッドの役割的なイメージです！

2021-05-18 14:38 UTC, hiyoko3 commented on src/lib/api/HotpepperApiForm.ts
> +const BudgetList: Array<Budget> = [
ここは特に取り決めしてなかったけど、この値はAPIから取得したレスポンスのはずなので、データモデルにあたるかと思います！
`src/lib/model/HotpepperBudgetModel.ts `とかかな？

2021-05-19 13:12 UTC, narugit commented
priceRange→minPrice, maxPriceに変更する。

2021-05-31 15:35 UTC, narugit commented on src/lib/api/HotpepperApi.ts
> +      let selectedShops = responseData.then(responses => {
bbc5b61205e6f1fa60d7265a4b38eb984fcc12cf にて対応しました！

2021-05-31 15:36 UTC, narugit commented on src/lib/api/HotpepperApiForm.ts
> +  public static newFromConfig(budgetMin: number, budgetMax: number, lat: number, lng: number): HotpepperApiFormImpl {
758939ba055bb61825363787f65ca9bf367e9b02 にて対応しました！

2021-05-31 15:36 UTC, narugit commented on src/lib/api/HotpepperApiForm.ts
> +const BudgetList: Array<Budget> = [
94bae78cb75b2068fc26e1f64f158cc9a81d4fc2 にて対応しました！

2021-05-31 15:46 UTC, narugit commented on src/commands/HotpepperSearch.ts
> +    const priceRange = generalConf.priceRange?.sort();
8300bdc92c9fae47ebb679eeb629b230f0d1cf54 にて対応しました！

2021-06-01 12:30 UTC, hiyoko3 approved these changes

2021-06-01 12:30 UTC, merged