[AP-7] Mofidy README
naruhiyo/appetizer pull request #22
Opened 2021-07-14 12:01 UTC by narugit

### 先行PR
無し

### 内容
[AP-7](https://naruhiyo.atlassian.net/browse/AP-7)

### 動作確認項目
READMEの見た目が意図通りに描画されていること

### 動作確認結果

### 備考
無し

2021-07-14 12:12 UTC, hiyoko3 approved these changes
`for developer`はお任せで

2021-07-14 12:14 UTC, narugit commented
- 手順2.と3.のスクショは不要
- GIFを作成する

2021-07-14 12:46 UTC, hiyoko3 commented
アプリの簡単な説明追加をお願いします。

2021-07-14 14:21 UTC, narugit commented on README.md
> +At lunchtime and dinner time, *Appetizer* introduce you to a restaurant near the station you specify.
```suggestion
At lunchtime and dinnertime, *Appetizer* introduce you to a restaurant near the station you specify.
```

2021-07-21 13:05 UTC, hiyoko3 requested changes

2021-07-21 13:05 UTC, hiyoko3 commented on README.md
> +<!-- TODO: .envのコピーとか書く？それかConfluenceにかいて消しちゃう？ -->
ここってどうするんだっけ？

2021-07-28 11:10 UTC, hiyoko3 approved these changes

2021-07-28 11:10 UTC, merged