Update package.json
naruhiyo/appetizer pull request #24
Opened 2021-07-14 14:22 UTC by narugit

### 先行PR
無し

### 内容
https://code.visualstudio.com/api/references/extension-manifest にて、package.jsonに加えたい情報を追加する。

### 動作確認項目
VSCode Market Place上に変更内容が反映されること

### 動作確認結果
未確認

### 備考
無し

2021-07-21 13:06 UTC, hiyoko3 requested changes

2021-07-23 07:01 UTC, narugit commented on package.json
> +  "license": "SEE LICENSE IN LICENSE",
なるほど

2021-07-23 07:02 UTC, narugit commented on package.json
> +  "license": "SEE LICENSE IN LICENSE",
```suggestion
  "license": "MIT",
```

2021-07-28 10:58 UTC, hiyoko3 approved these changes

2021-07-28 11:11 UTC, merged