[AP-9] Get current time
naruhiyo/appetizer pull request #3
Opened 2021-02-08 14:33 UTC by narugit

### 先行PR
無し

### 内容
現在時刻を取得する関数を追加しました。

### 動作確認項目
- `appetizer.showCurrentTime()`を実行時に現在時刻を取得できること

### 動作確認結果
![image](https://user-images.githubusercontent.com/28133383/107233381-ddc74f80-6a65-11eb-9c8f-c3a0db0d0a89.png)

### 備考
無し

2021-02-08 15:31 UTC, hiyoko3 requested changes
https://qiita.com/egnr-in-6matroom/items/37e65bb642d2e158804c
こことか参考になりそう

2021-02-08 15:31 UTC, hiyoko3 commented on src/commands/Timer.ts
> +  const month = date.getMonth()
```suggestion
  const month = date.getMonth() + 1
```

2021-02-08 15:31 UTC, hiyoko3 commented on src/commands/Timer.ts
> +  const day = date.getDay()
```suggestion
  const day = date.getDate()
```

2021-02-08 23:08 UTC, narugit commented
ありがとう！ボケてた、、

2021-02-09 12:33 UTC, hiyoko3 requested changes

2021-02-09 12:33 UTC, hiyoko3 commented on src/commands/Timer.ts
> +    vscode.window.showInformationMessage(`Now: ${currentTime.year}/${currentTime.month}/${currentTime.date} ${currentTime.hour}:${currentTime.minute}:${currentTime.second}`);
処理が長いので変数に入れたいですね

2021-02-09 12:58 UTC, hiyoko3 approved these changes

2021-02-09 13:01 UTC, merged