[AP-21] Activate when launching
naruhiyo/appetizer pull request #6
Opened 2021-03-11 14:03 UTC by narugit

### 先行PR
無し

### 内容
VS Code起動時に本拡張機能をアクティベートする

### 動作確認項目
起動後、何も操作せずとも、タイマ発火による`appetizer.showCurrentTime()`が実行されること

### 動作確認結果
無し

### 備考
無し

2021-03-17 14:14 UTC, hiyoko3 requested changes

2021-03-17 14:14 UTC, hiyoko3 commented on package.json
> +		"*"
これって、例えばコマンド入力も受け付けてしまうと思うのですが、それはしょうがない感じですかね？

2021-03-17 14:17 UTC, TE-NarukiTanabe commented on package.json
> +		"*"
https://code.visualstudio.com/api/references/activation-events#Start-up
これ見る限り、起動時のみにしか呼ばれなさそう

2021-03-17 14:20 UTC, narugit commented on package.json
> +		"*"
https://code.visualstudio.com/api/references/activation-events#Start-up
これ見る限り、起動時のみにしか呼ばれなさそう

2021-03-17 14:22 UTC, hiyoko3 commented on package.json
> +		"*"
起動時、というより、VSCodeの起動後から拡張機能が動作し始めたほうが良さそうだから、`onStartupFinished`に変えませんか？

2021-03-23 12:26 UTC, narugit commented on package.json
> +		"*"
f77818c で対応しました

2021-03-23 12:37 UTC, hiyoko3 approved these changes

2021-03-23 12:38 UTC, merged